[project]
name = "golden-beach"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.15",
    "mkdocstrings-python>=1.16.12",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
]
